Repository projectcalico/node, pull requests merged in 2018-09, with the labels that each got.

#55 Streamline templating for 'rr client' vs 'next hop self'
  filesystem/etc/calico/confd/templates/bird.cfg.template
Labels: release-note-required

#61 Image: Add ca-certificates package
  Dockerfile.amd64
  Dockerfile.arm64
  Dockerfile.ppc64le
  Dockerfile.s390x
Labels: cherry-pick-candidate

#63 Fix release
  Makefile
Labels: cherry-pick-candidate

#66 Fix version check
  Makefile
Labels: cherry-pick-completed

#72 release-v3.2 cherry-pick: add nsswitch.conf
  filesystem/etc/nsswitch.conf
Labels: release-note-required
