Repository projectcalico/node, pull requests merged in 2019-08, with the labels that each got.

#285 Fix scapy binary in ip spoofing
  tests/k8st/tests/test_ipip_spoofing.py
Labels: docs-not-required, release-note-not-required

#286 Update Felix pin for release-v3.5
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-required

#287 Update Felix pin for release-v3.6
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-required

#288 Update Felix pin for release-v3.7
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-required

#289 Update Felix pin for release-v3.8
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-required

#273 switch node to go modules from glide
  Dockerfile.amd64
  Dockerfile.arm64
  Dockerfile.ppc64le
  Dockerfile.s390x
  Makefile
  buildinfo/buildinfo.go
  cmd/calico-node/main.go
  glide.lock
  glide.yaml
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#292 cleanup: fix error message typos in startup.go
  pkg/startup/startup.go
Labels: docs-not-required, release-note-not-required

#291 Update OSS semaphore jobs that depend on glide
  Makefile
Labels: docs-not-required, release-note-not-required

#294 Update Felix pin for release-v3.2
  glide.lock
  glide.yaml
Labels: docs-pr-required, release-note-required

#293 Update felix pin for release-v3.3
  glide.lock
  glide.yaml
Labels: docs-pr-required, release-note-required

#295 Makefile: go commands must run insde docker
  Makefile
Labels: docs-not-required, release-note-not-required

#296 Fix missing node templates in built images
  Makefile
Labels: docs-not-required, release-note-not-required

#283 Enable VXLAN when VXLANMode is CrossSubnet
  pkg/allocateip/allocateip.go
  pkg/allocateip/allocateip_test.go
  pkg/startup/startup.go
Labels: docs-not-required, release-note-not-required

#298 Pass in user.name and user.email instead of --author in git-commit, and define GOPATH for go modules cachine when it is not specified by the environment
  Makefile
Labels: docs-not-required, release-note-not-required

#305 Fix update pin target
  Makefile
Labels: docs-not-required, release-note-not-required

#309 Use libcalico-go logutils and update Felix pin
  go.mod
  go.sum
  pkg/allocateip/allocateip.go
Labels: docs-not-required, release-note-not-required
