Repository projectcalico/node, pull requests merged in 2019-11, with the labels that each got.

#363 [release-v3.10] Automatic patch of libcalico-go to 8f81e1e344ce1dc436b066ea242e4da5df765a97
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#364 [release-v3.9] Automatic patch of libcalico-go to 1891db7ae73bcafe01c90943f5eaac25ec53c96d
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#365 Similar fix for DOCKER_EXTRA_ARGS for importing lib-calico.go
  Makefile
Labels: docs-not-required, release-note-not-required

#366 Pin ubi-minimal image to 8.0
  Dockerfile.amd64
Labels: docs-not-required, release-note-not-required

#368 Update Makefile to clean pkg-cache
  Makefile
Labels: docs-not-required, release-note-not-required

#370 Move common Makefile targets to Makefile.common
  Makefile
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#369 Adding service checks for confd, bird and bird6 on the liveness probe
  cmd/calico-node/main.go
  pkg/health/health.go
  tests/st/bgp/test_bgp.py
  tests/st/utils/docker_host.py
Labels: cherry-pick-candidate, docs-pr-required, release-note-required

#371 Switch Makefile.common from wget to curl, remove wget dependency
  Makefile
Labels: docs-not-required, release-note-not-required

#373 [PATCH] Update Release v3.9
  cmd/calico-node/main.go
  pkg/health/health.go
  tests/st/bgp/test_bgp.py
  tests/st/utils/docker_host.py
Labels: docs-pr-required, release-note-required

#372 [PATCH] Update Release v3.10
  cmd/calico-node/main.go
  pkg/health/health.go
  tests/st/bgp/test_bgp.py
  tests/st/utils/docker_host.py
Labels: docs-pr-required, release-note-required

#376 make update-pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#377 Move build/push targets back to local Makefile
  Makefile
Labels: docs-not-required, release-note-not-required

#374 [PATCH] Update Release v3.8
  cmd/calico-node/main.go
  pkg/health/bird/bird.go
  pkg/health/health.go
  tests/st/bgp/test_bgp.py
  tests/st/utils/docker_host.py
Labels: docs-pr-required, release-note-required

#378 Move image build/push targets back to local Makefile (add join_platfo…
  Makefile
Labels: docs-not-required, release-note-not-required
