Repository projectcalico/node, pull requests merged in 2019-04, with the labels that each got.

#207 Fix for ipset error
  Dockerfile.amd64
Labels: docs-not-required, release-note-not-required

#205 Update node to assign VXLAN tunnel addresses and VXLAN IP pools
  Makefile
  cmd/calico-node/main.go
  filesystem/etc/rc.local
  glide.lock
  glide.yaml
  pkg/allocateip/allocateip.go
  pkg/allocateip/allocateip_suite_test.go
  pkg/allocateip/allocateip_test.go
  pkg/allocateip/test_utils.go
  pkg/allocateipip/allocate_ipip_addr.go
  pkg/allocateipip/allocate_ipip_addr_test.go
  pkg/startup/startup.go
Labels: release-note-required

#209 Add a "vxlan" (only) networking mode.
  filesystem/etc/rc.local
Labels: docs-pr-required, release-note-required

#211 [master] Automatic update of libcalico-go to 727a39e77d674af6e7d6684b941916183d80f5de
  glide.lock
  glide.yaml
Labels: docs-pr-required, release-note-required

#212 Remove logging during readiness check
  cmd/calico-node/main.go
Labels: docs-not-required, release-note-not-required

#208 Add new tool to the image and bump Felix
  Dockerfile.amd64
  Dockerfile.arm64
  Dockerfile.ppc64le
  Dockerfile.s390x
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required

#215 [master] Automatic patch of libcalico-go to 43c1da882b70aba9d0325e7de4393439ef202550
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required

#216 make run-k8s-apiserver: do not report err waiting for docker
  Makefile
Labels: docs-not-required, release-note-not-required

#217 vendor: bump felix
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required

#218 Don't allocate a tunnel address if using k8s pod CIDR allocations
  glide.lock
  glide.yaml
  pkg/allocateip/allocateip.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#222 [release-v3.7] Automatic patch of libcalico-go to 6860ff2cfd923a870ff7a76563ce825d6e47adb8
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required

#221 [release-v3.5] Automatic patch of libcalico-go to aae6c757ef3745eb6ecb45351470e66c54fd9e13
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required

#220 [release-v3.6] Automatic patch of libcalico-go to 24a5a971c54bf0f43417bbfccd0b31e7ffa19a98
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required
