Repository projectcalico/node, pull requests merged in 2019-05, with the labels that each got.

#223 Switching image base to debian:9.8-slim
  Dockerfile.amd64
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#224 Switching image base to debian:9.8-slim
  Dockerfile.amd64
Labels: docs-not-required, release-note-required

#227 Pin version of calicoctl in STs
  Makefile
Labels: docs-not-required, release-note-not-required

#228 Pin test dependencies to branch
  Makefile
Labels: docs-not-required, release-note-not-required

#229 Pin test dependencies to branch
  Makefile
Labels: docs-not-required, release-note-not-required

#230 Pin test dependencies to branch
  Makefile
Labels: docs-not-required, release-note-not-required

#232 Install backported iproute2, needed for BPF.
  Dockerfile.amd64
Labels: cherry-pick-candidate, docs-not-required, release-note-required

#233 Automated cherry pick of #232: Install backported iproute2, needed for BPF.
  Dockerfile.amd64
Labels: docs-not-required, release-note-required

#225 Always rebuild when DEV_BUILD=true
  Makefile
Labels: docs-not-required, release-note-not-required

#234 Clean up BGP config after service advertisement tests
  tests/k8st/tests/test_bgp_advert.py
  tests/k8st/utils/utils.py
  tests/st/utils/utils.py
Labels: docs-not-required, release-note-not-required

#235 Check for OOM kills when a test fails
  tests/st/utils/docker_host.py
Labels: docs-not-required, release-note-not-required

#236 Wait for access pod running
  tests/k8st/test_base.py
  tests/k8st/tests/test_bgp_advert.py
  tests/k8st/tests/test_simple.py
  tests/k8st/utils/utils.py
Labels: docs-not-required, release-note-not-required

#231 Fix calicoctl update and usage
  Makefile
Labels: docs-not-required, release-note-not-required

#238 Increase K8S version to 1.14.1
  Makefile
Labels: docs-not-required, release-note-not-required

#237 update confd pin for release-v3.6
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required

#239 Backport k8st flake fixes to release-v3.6
  tests/k8st/test_base.py
  tests/k8st/tests/test_bgp_advert.py
  tests/k8st/tests/test_simple.py
  tests/k8st/utils/utils.py
  tests/st/utils/utils.py
Labels: docs-pr-required, release-note-required
