Repository projectcalico/node, pull requests merged in 2019-07, with the labels that each got.

#263 Add spoof tests
  tests/k8st/infra/calicoctl-etcd.yaml
  tests/k8st/tests/test_ipip_spoofing.py
  tests/k8st/utils/utils.py
Labels: docs-pr-required, release-note-required

#264 Use iptables 1.8 with amd64 image
  Dockerfile.amd64
Labels: docs-not-required, release-note-required

#241 Configurable port for Felix liveness / readiness probes
  cmd/calico-node/main.go
  pkg/health/bird/bird.go
  pkg/health/health.go
  tests/st/bgp/test_bgp.py
  tests/st/utils/docker_host.py
Labels: cherry-pick-candidate, docs-not-required, release-note-required

#266 Remove references to libnetwork as this is no longer part of calico/node
  .gitignore
  Dockerfile.ppc64le
  Dockerfile.s390x
  filesystem/etc/rc.local
  filesystem/etc/service/available/libnetwork/log/run
  filesystem/etc/service/available/libnetwork/run
  tests/st/bgp/test_backends.py
  tests/st/bgp/test_global_config.py
  tests/st/bgp/test_global_peers.py
  tests/st/bgp/test_node_peers.py
  tests/st/ipam/test_ipam.py
  tests/st/libnetwork/test_labeling.py
  tests/st/policy/test_profile.py
  tests/st/utils/docker_host.py
  tests/st/utils/network.py
  tests/st/utils/workload.py
Labels: docs-not-required, release-note-not-required

#267 [v3.8] backport iptables v1.8.x support
  Dockerfile.amd64
  glide.lock
  glide.yaml
Labels: docs-pr-required, release-note-required

#268 [release-v3.8] Automatic patch of libcalico-go to ac36d966132f2019eb4afc4d3823ed2a98564d2f
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required

#254 Fix issues where tunnel ip been reused incorrectly in kdd mode.
  pkg/allocateip/allocateip.go
  pkg/allocateip/allocateip_test.go
  pkg/allocateip/test_utils.go
Labels: docs-not-required, release-note-required

#269 Adjust some log messages
  pkg/allocateip/allocateip.go
Labels: docs-not-required, release-note-not-required

#272 Update vendor pins
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required

#274 Update to use debian:10-slim
  Dockerfile.amd64
Labels: docs-not-required, release-note-required

#275 Use debian 10 as base image
  Dockerfile.amd64
Labels: docs-not-required, release-note-required
