Repository projectcalico/node, pull requests merged in 2019-06, with the labels that each got.

#244 make update-felix-confd-libcalico, for KDD host-local IPAM fix
  glide.lock
  glide.yaml
Labels: docs-pr-required, release-note-required

#243 runsvdir is not in the same location for different base images
  filesystem/sbin/start_runit
Labels: cherry-pick-candidate, docs-not-required, release-note-required

#245 Automated cherry pick of #243: runsvdir is not in the same location for different base
  filesystem/sbin/start_runit
Labels: docs-not-required, release-note-required

#246 Update felix pin
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required

#247 release-v3.7: Update libcalico, confd, and felix pins
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required

#248 release-v3.5: Update libcalico, confd, and felix pins
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required

#250 Remove stray files that made it into master
  fakefile
  fakefile2
Labels: docs-not-required, release-note-not-required

#252 Update pins to pickup sockmap name change.
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required

#251 Rev felix to pick up sidecar acceleration flag name change.
  glide.lock
  glide.yaml
Labels: docs-completed, release-note-not-required

#253 Rev felix and libcalico-go.
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required

#256 Update vendor dir
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required

#257 Handle nil BGP spec in tunnel address removal
  pkg/allocateip/allocateip.go
Labels: docs-not-required, release-note-required

#258 make update-felix-confd-libcalico, to disallow XDP config
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required

#259 Update vendor to pull in new felix
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required

#261 Update vendor to pull in new felix
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required

#260 Update vendor to pull in new felix
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required

#262 Update vendor to pull in new felix
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required
