Repository projectcalico/node, pull requests merged in 2019-10, with the labels that each got.

#333 Update node k8st's for new BGPConfig serviceExternalIPs and serviceClusterIPs fields
  tests/k8st/infra/calicoctl-etcd.yaml
  tests/k8st/tests/test_bgp_advert.py
Labels: docs-not-required, release-note-not-required

#334 need to harden go mod downloads against network errors
  Makefile
  go.mod
Labels: docs-not-required, release-note-not-required

#340 Add pin updates for libcalico
  Makefile
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#343 Add NodeSelector env var for default pools
  pkg/startup/startup.go
  pkg/startup/startup_test.go
Labels: cherry-pick-candidate, docs-pr-required, release-note-required

#346 Picking NodeSelector and BlockSize for default pools
  pkg/allocateip/allocateip.go
  pkg/startup/startup.go
  pkg/startup/startup_test.go
Labels: docs-pr-required, release-note-required

#345 K8ST: Work around unavailability of Docker repo
  tests/k8st/utils/utils.py
Labels: docs-not-required, release-note-not-required

#284 update licenses
  filesystem/licenses/app-policy-license-report.md
  filesystem/licenses/calicoctl-license-report.md
  filesystem/licenses/cni-plugin-license-report.md
  filesystem/licenses/confd-license-report.md
  filesystem/licenses/felix-license-report.md
  filesystem/licenses/kube-controllers-license-report.md
  filesystem/licenses/node-license-report.md
  filesystem/licenses/typha-license-report.md
Labels: docs-not-required, release-note-not-required

#344 Enable node to update CNI kubeconfig as needed
  cmd/calico-node/main.go
  filesystem/etc/rc.local
  filesystem/etc/service/available/cni/log/run
  filesystem/etc/service/available/cni/run
  go.mod
  go.sum
  pkg/cni/token_watch.go
Labels: cherry-pick-candidate, docs-pr-required, release-note-required

#342 Fix flake in GCE RR tests
  tests/st/bgp/test_ipip.py
Labels: docs-not-required, release-note-not-required

#349 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#347 [release-v3.8] BoundServiceAccountToken volume support
  cmd/calico-node/main.go
  filesystem/etc/rc.local
  filesystem/etc/service/available/cni/log/run
  filesystem/etc/service/available/cni/run
  glide.lock
  glide.yaml
  pkg/cni/token_watch.go
Labels: docs-pr-required, release-note-required

#350 [release-v3.9] Token projection support
  cmd/calico-node/main.go
  filesystem/etc/rc.local
  filesystem/etc/service/available/cni/log/run
  filesystem/etc/service/available/cni/run
  go.mod
  go.sum
  pkg/cni/token_watch.go
Labels: docs-not-required, release-note-required

#341 [release-v3.10] Automatic update of libcalico-go to 399044ecb65942961586f38c38415d95b9122dcc
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#351 Run an apt-upgrade to make sure we're using the latest packages
  Dockerfile.amd64
Labels: docs-not-required, release-note-required

#352 Run an apt-upgrade to make sure we're using the latest packages
  Dockerfile.amd64
Labels: docs-not-required, release-note-required

#354 Run an apt-upgrade to make sure we're using the latest packages
  Dockerfile.amd64
Labels: docs-not-required, release-note-not-required

#353 Run an apt-upgrade to make sure we're using the latest packages
  Dockerfile.amd64
Labels: docs-not-required, hold-merge, release-note-required

#356 fix some wrong format
  tests/k8st/infra/calico-kdd.yaml
Labels: docs-pr-required, release-note-required

#357 Remove 'undo' behavior from local_build
  Makefile
Labels: docs-not-required, release-note-not-required

#358 use arm64 image for etcd when Dockerfile is arm64
  calico_test/Dockerfile.arm64.calico_test
Labels: docs-not-required, release-note-not-required

#359 Update BIRD for CVE-2019-16159
  Makefile
Labels: docs-not-required, release-note-required

#361 Makefile: fix sh issue
  Makefile
Labels: docs-pr-required, release-note-required

#362 Use ubi-minimal for amd64 image
  .dockerignore
  Dockerfile.amd64
  Makefile
  centos.repo
Labels: docs-not-required, release-note-required
