Repository projectcalico/node, pull requests merged in 2020-10, with the labels that each got.

#580 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#581 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#582 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#584 Update pins (for BGP password support)
  Makefile
  go.mod
  go.sum
  tests/k8st/infra/calico-etcd.yaml
  tests/k8st/infra/calico-kdd.yaml
  tests/k8st/infra/calicoctl-etcd.yaml
  tests/k8st/infra/calicoctl.yaml
  tests/k8st/tests/test_bgp_advert.py
Labels: docs-pr-required, release-note-required

#586 Automated cherry pick of #569: if calico isn't being used for networking, don't restart
  pkg/startup/startup.go
  pkg/startup/startup_test.go
Labels: docs-not-required, release-note-required

#585 Update go-build version to v0.48 (go 1.15.2)
  Makefile
Labels: docs-not-required, release-note-not-required

#587 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#588 Added BGP Windows support
  Makefile
  cmd/calico-node/main.go
  go.mod
  go.sum
  pkg/startup/startup_windows.go
  windows-packaging/CalicoWindows/confd/conf.d/.gitignore
  windows-packaging/CalicoWindows/confd/confd-service.ps1
  windows-packaging/CalicoWindows/confd/templates/.gitignore
  windows-packaging/CalicoWindows/config.ps1
  windows-packaging/CalicoWindows/install-calico.ps1
  windows-packaging/CalicoWindows/libs/calico/calico.psm1
  windows-packaging/CalicoWindows/node/node-service.ps1
  windows-packaging/CalicoWindows/start-calico.ps1
  windows-packaging/CalicoWindows/stop-calico.ps1
  windows-packaging/CalicoWindows/uninstall-calico.ps1
Labels: docs-pr-required, release-note-required

#590 Semaphore Auto Pin Update PR
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#589 windows: kube-services scripts support single service
  windows-packaging/CalicoWindows/kubernetes/install-kube-services.ps1
  windows-packaging/CalicoWindows/kubernetes/uninstall-kube-services.ps1
Labels: docs-not-required, release-note-not-required

#532 Fixed s390x native build
  Dockerfile.s390x
  calico_test/Dockerfile.s390x.calico_test
  workload/Dockerfile.s390x
Labels: docs-not-required, merge-when-ready, release-note-required

#595 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#583 Fix DNS resolution in calico-node containers
  clean-up-filesystem.sh
Labels: cherry-pick-candidate, docs-not-required, merge-when-ready, release-note-required

#599 Update felix version
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#601 Reduce log level for spammy log
  pkg/startup/startup.go
Labels: docs-not-required, release-note-not-required

#594 Rename semaphore job name for Windows
  .semaphore/semaphore.yml
Labels: docs-pr-required, release-note-required

#604 Automatic restore aws metadata server route
  .semaphore/semaphore.yml
  windows-packaging/CalicoWindows/libs/calico/calico.psm1
  windows-packaging/CalicoWindows/node/node-service.ps1
Labels: docs-pr-required, release-note-required

#607 mirror.centos.org -> vault.centos.org
  centos.repo
Labels: docs-not-required, merge-when-ready, release-note-not-required

#606 Added OSType to ClusterInformation
  pkg/startup/startup.go
  pkg/startup/startup_linux.go
  pkg/startup/startup_test.go
  pkg/startup/startup_windows.go
Labels: docs-not-required, release-note-not-required

#610 Automated cherry pick of #607: mirror.centos.org -> vault.centos.org
  centos.repo
Labels: docs-not-required, release-note-not-required

#609 Automated cherry pick of #607: mirror.centos.org -> vault.centos.org
  centos.repo
Labels: docs-not-required, release-note-not-required
