Repository projectcalico/node, pull requests merged in 2020-09, with the labels that each got.

#565 [release-v3.15] Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#566 [release-v3.16] Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#544 Use calicoctl verison poller instead of now removed calicoctl-wait
  tests/k8st/infra/calicoctl-etcd.yaml
  tests/k8st/infra/calicoctl.yaml
Labels: docs-not-required, release-note-not-required

#567 Auto detect Calico path for Windows.
  windows-packaging/CalicoWindows/felix/felix-service.ps1
  windows-packaging/CalicoWindows/kubernetes/README.txt
  windows-packaging/CalicoWindows/kubernetes/kube-proxy-service.ps1
  windows-packaging/CalicoWindows/kubernetes/kubelet-service.ps1
  windows-packaging/CalicoWindows/node/node-service.ps1
Labels: docs-not-required, release-note-not-required

#569 Conditionally terminate if IP isn't available under calico/node resource.
  pkg/startup/startup.go
  pkg/startup/startup_test.go
Labels: docs-not-required, release-note-not-required

#570 feature(Windows): Allow to automatically set etcd TLS config
  windows-packaging/CalicoWindows/config.ps1
Labels: docs-pr-required, release-note-required

#574 Add update pin pipeline and auto promotion for pipeline
  .semaphore/semaphore.yml
  .semaphore/update-pins.yml
  .semaphore/update_pins.yml
  Makefile
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#575 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: docs-not-required, merge-when-ready, release-note-not-required

#577 Adjust service advertisement test to cover using BGP password
  go.mod
  go.sum
  tests/k8st/infra/calico-etcd.yaml
  tests/k8st/infra/calico-kdd.yaml
  tests/k8st/tests/test_bgp_advert.py
Labels: docs-pr-required, release-note-required

#578 Allow semaphore-run-auto-pin-update-workflows to set the SEMAPHORE_PROJECT_ID (only default it if it's not set)
  Makefile
Labels: docs-not-required, release-note-not-required

#579 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required
