Repository projectcalico/node, pull requests merged in 2020-03, with the labels that each got.

#432 Update go mod pins
  .gitignore
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#423 Run checks in parallel
  go.mod
  pkg/health/health.go
Labels: docs-not-required, release-note-required

#434 Rev felix to pick up BPF map GC fix.
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#421 Autoselect default IP pool if overlapping with host IPs
  go.mod
  pkg/startup/autodetection/ipv4/poolselector.go
  pkg/startup/autodetection/ipv4/poolselector_test.go
  pkg/startup/startup.go
  pkg/startup/startup_test.go
Labels: docs-pr-required, release-note-required

#435 bpf: MTU fixes
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#438 Update Felix pin for BPF MTU fix
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#437 Update included calico.yaml to latest master
  tests/k8st/infra/calico-kdd.yaml
Labels: docs-not-required, release-note-not-required

#430 Don't leak old tunnel addresses
  go.mod
  go.sum
  pkg/allocateip/allocateip.go
  pkg/allocateip/allocateip_test.go
Labels: cherry-pick-candidate, docs-not-required, release-note-required

#441 Use calico/kube-controllers:release-v3.13 instead of master
  tests/k8st/infra/calico-etcd.yaml
  tests/k8st/infra/calico-kdd.yaml
Labels: docs-not-required, release-note-not-required

#442 Allow more time for CI in Semaphore v2
  .semaphore/semaphore.yml
Labels: docs-not-required, release-note-not-required

#440 Minor speed improvements
  tests/st/ipam/test_ipam.py
  tests/st/utils/utils.py
Labels: docs-not-required, release-note-not-required

#436 Release tunnel addresses if the node object doesn't match
  go.sum
  pkg/allocateip/allocateip.go
  pkg/allocateip/allocateip_test.go
Labels: docs-not-required, release-note-required

#424 Add graceful restart test
  tests/k8st/tests/test_simple.py
Labels: docs-not-required, release-note-not-required

#444 Automated cherry pick of #430 origin release v3.13
  go.mod
  go.sum
  pkg/allocateip/allocateip.go
  pkg/allocateip/allocateip_test.go
Labels: docs-not-required, release-note-required

#443 Release tunnel addresses by handle
  pkg/allocateip/allocateip.go
  pkg/allocateip/allocateip_test.go
Labels: docs-not-required, release-note-required

#446 Automated cherry pick of #436: Don't leak addresses if the node object is modified
  go.sum
  pkg/allocateip/allocateip.go
  pkg/allocateip/allocateip_test.go
Labels: docs-pr-required, release-note-required

#445 Automated cherry pick of #430: Add test which catches IP leak
  .semaphore/semaphore.yml
  go.mod
  go.sum
  pkg/allocateip/allocateip.go
  pkg/allocateip/allocateip_test.go
  tests/k8st/infra/calico-etcd.yaml
  tests/k8st/infra/calico-kdd.yaml
Labels: docs-not-required, release-note-required

#448 Include BIRD source in docker image
  .gitignore
  Makefile
Labels: docs-not-required, release-note-not-required

#449 Update license files included in calico/node
  filesystem/licenses/Apache-2.0
  filesystem/licenses/BSD
  filesystem/licenses/GPLv2
  filesystem/licenses/ISC
  filesystem/licenses/MIT
  filesystem/licenses/Mozilla-public
  filesystem/licenses/app-policy-license-report.md
  filesystem/licenses/calicoctl-license-report.md
  filesystem/licenses/cni-plugin-license-report.md
  filesystem/licenses/confd-license-report.md
  filesystem/licenses/felix-license-report.md
  filesystem/licenses/kube-controllers-license-report.md
  filesystem/licenses/node-license-report.md
  filesystem/licenses/typha-license-report.md
Labels: docs-not-required, release-note-required

#456 Always use latest UBI
  Dockerfile.amd64
Labels: docs-not-required, release-note-not-required

#455 Always use latest UBI
  Dockerfile.amd64
Labels: docs-not-required, release-note-not-required

#454 Update UBI base image version
  Dockerfile.amd64
Labels: docs-not-required, release-note-not-required

#453 Add additional licenses to image
  README.md
  filesystem/licenses/Apache-2.0
  filesystem/licenses/BSD
  filesystem/licenses/ISC
  filesystem/licenses/MIT
  filesystem/licenses/Mozilla-public
Labels: docs-not-required, release-note-not-required
