Repository projectcalico/node, pull requests merged in 2020-08, with the labels that each got.

#540 Remove vendor dir if it exists on clean
  Makefile
Labels: docs-not-required, release-note-not-required

#541 Don't fail if not authorized to access configmaps
  pkg/startup/startup.go
Labels: docs-not-required, release-note-required

#542 Added Windows packaging
  .semaphore/semaphore.yml
  Makefile
  cmd/calico-ipam/calico-ipam.go
  cmd/calico/calico.go
  cmd/calico/calico_suite_test.go
  cmd/calico/cni_conf_test.go
  go.mod
  go.sum
  pkg/startup/autodetection/ipv4/poolselector.go
  pkg/startup/autodetection/ipv4/poolselector_test.go
  pkg/startup/autodetection/ipv4/poolselector_windows.go
  pkg/startup/startup.go
  pkg/startup/startup_linux.go
  pkg/startup/startup_windows.go
  windows-packaging/.gitignore
  windows-packaging/CalicoWindows/README.txt
  windows-packaging/CalicoWindows/calico-kube-config.template
  windows-packaging/CalicoWindows/cni.conf.template
  windows-packaging/CalicoWindows/cni/.gitignore
  windows-packaging/CalicoWindows/config.ps1
  windows-packaging/CalicoWindows/felix/felix-service.ps1
  windows-packaging/CalicoWindows/install-calico.ps1
  windows-packaging/CalicoWindows/kubernetes/README.txt
  windows-packaging/CalicoWindows/kubernetes/install-kube-services.ps1
  windows-packaging/CalicoWindows/kubernetes/kube-proxy-service.ps1
  windows-packaging/CalicoWindows/kubernetes/kubelet-service.ps1
  windows-packaging/CalicoWindows/kubernetes/uninstall-kube-services.ps1
  windows-packaging/CalicoWindows/libs/calico/calico.psm1
  windows-packaging/CalicoWindows/libs/hns/.gitignore
  windows-packaging/CalicoWindows/node/node-service.ps1
  windows-packaging/CalicoWindows/start-calico.ps1
  windows-packaging/CalicoWindows/stop-calico.ps1
  windows-packaging/CalicoWindows/uninstall-calico.ps1
  windows-packaging/nssm-2.24.zip
  windows-packaging/nssm.sha256sum
Labels: docs-pr-required, release-note-required

#533 Update to latest BIRD code, to avoid needing -s
  Makefile
Labels: docs-not-required, release-note-not-required

#529 Fix issue when remote_deps generated twice
  Makefile
Labels: docs-not-required, release-note-not-required

#546 Pin calicoctl and cni-plugin versions used in tests
  Makefile
  tests/k8st/infra/calico-etcd.yaml
  tests/k8st/infra/calico-kdd.yaml
  tests/k8st/infra/calicoctl-etcd.yaml
  tests/k8st/infra/calicoctl.yaml
Labels: docs-not-required, release-note-not-required

#547 Pin calicoctl and cni-plugin versions used in tests
  Makefile
  tests/k8st/infra/calico-etcd.yaml
  tests/k8st/infra/calico-kdd.yaml
  tests/k8st/infra/calicoctl-etcd.yaml
  tests/k8st/infra/calicoctl.yaml
Labels: docs-not-required, release-note-not-required

#548 [v3.16] Update pins to pick up BPF fixes.
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#553 Cherry-picking #549 from master for monitoring node IP addresses
  cmd/calico-node/main.go
  filesystem/etc/rc.local
  filesystem/etc/service/available/monitor-addresses/log/run
  filesystem/etc/service/available/monitor-addresses/run
  pkg/startup/startup.go
  pkg/startup/startup_test.go
Labels: docs-pr-required, release-note-required

#554 Cherry-picking #549 from master for monitoring node IP addresses
  cmd/calico-node/main.go
  filesystem/etc/rc.local
  filesystem/etc/service/available/monitor-addresses/log/run
  filesystem/etc/service/available/monitor-addresses/run
  pkg/startup/startup.go
  pkg/startup/startup_test.go
Labels: docs-pr-required, release-note-required

#555 Added windows release process
  Makefile
Labels: cherry-pick-candidate, docs-pr-required, release-note-required

#556 Cherry-pick Added windows release process
  Makefile
Labels: docs-not-required, release-note-not-required

#557 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#558 Use rwx(o+g) for monitor-addresses runs files
  filesystem/etc/service/available/monitor-addresses/log/run
  filesystem/etc/service/available/monitor-addresses/run
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#559 Use rwx(o+g) for monitor-addresses runs files
  filesystem/etc/service/available/monitor-addresses/log/run
  filesystem/etc/service/available/monitor-addresses/run
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#560 cherry-pick #559 from master
  filesystem/etc/service/available/monitor-addresses/log/run
  filesystem/etc/service/available/monitor-addresses/run
Labels: docs-not-required, release-note-not-required

#561 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#562 Update felix pin
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required
