Repository projectcalico/node, pull requests merged in 2020-02, with the labels that each got.

#417 Auto-detect Pod CIDR on kubeadm
  go.mod
  go.sum
  pkg/startup/startup.go
  pkg/startup/startup_test.go
Labels: docs-not-required, release-note-required

#420 Add RBAC for configmaps, for kubeadm CIDR auto-detection
  .semaphore/semaphore.yml
  go.sum
  tests/k8st/delete_kind_cluster.sh
  tests/k8st/infra/calico-etcd.yaml
  tests/k8st/infra/calico-kdd.yaml
Labels: docs-not-required, release-note-not-required

#422 Clean up confd directory before recreating it.
  Makefile
Labels: docs-pr-required, release-note-required

#425 Automated cherry pick of #422: Clean up confd directory before recreating it.
  Makefile
Labels: docs-not-required, release-note-not-required

#427 Add eBPF Dataplane tech preview
  .gitignore
  Dockerfile.amd64
  Makefile
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#429 Move remaining build steps to semaphore v2
  .semaphore/semaphore.yml
Labels: docs-not-required, release-note-not-required
