Repository projectcalico/node, pull requests merged in 2020-06, with the labels that each got.

#510 Pr calico node more logs
  pkg/startup/startup.go
Labels: docs-not-required, release-note-not-required

#509 By default, exclude cni.* from auto detection
  pkg/startup/startup_linux.go
Labels: docs-pr-required, release-note-required

#508 Use a tunnel IP allocation daemon rather than using confd to trigger IP allocations
  cmd/calico-node/main.go
  filesystem/etc/rc.local
  filesystem/etc/service/available/allocate-tunnel-addrs/log/run
  filesystem/etc/service/available/allocate-tunnel-addrs/run
  go.mod
  go.sum
  pkg/allocateip/allocateip.go
  pkg/allocateip/allocateip_suite_test.go
  pkg/allocateip/allocateip_test.go
  pkg/allocateip/test_utils.go
Labels: docs-not-required, release-note-not-required

#516 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-required

#517 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#521 Update libcalico-go pin
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#513 Properly handle disabled autodetection
  pkg/startup/startup.go
Labels: docs-not-required, release-note-required

#525 Attempt to clean up as many base image files as possible
  .dockerignore
  Dockerfile.amd64
  clean-up-filesystem.sh
  go.mod
  go.sum
  tests/st/bgp/test_bgp.py
Labels: docs-not-required, release-note-required
