Repository projectcalico/node, pull requests merged in 2020-01, with the labels that each got.

#385 Use new BIRD without orig_gw hack
  Makefile
Labels: docs-not-required, release-note-required

#395 Fix pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#399 Remove the 'calicoctl node checksystem' test
  tests/st/calicoctl/test_node_checksystem.py
Labels: docs-not-required, release-note-not-required

#398 release-v3.8 - Update pins
  glide.lock
  glide.yaml
  tests/st/calicoctl/test_node_checksystem.py
Labels: docs-not-required, release-note-not-required

#397 release-v3.9 - Update pins
  go.mod
  go.sum
  tests/st/calicoctl/test_node_checksystem.py
Labels: docs-not-required, release-note-not-required

#396 release-v3.10 - Update pins
  go.mod
  go.sum
  tests/st/calicoctl/test_node_checksystem.py
Labels: docs-not-required, release-note-not-required

#400 release-v3.8 - Update felix
  glide.lock
Labels: docs-not-required, release-note-not-required

#401 release-v3.9 - Update felix
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#402 release-v3.10 - Update felix
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#405 Add missing dependency to go.mod
  go.mod
Labels: docs-not-required, release-note-not-required

#404 Pin calicoctl to v3.11 instead of master (for release-v3.11)
  Makefile
Labels: docs-not-required, release-note-not-required

#409 Upstream centos:8 changed so fixing for 8.1 packages
  Dockerfile.amd64
Labels: docs-not-required, release-note-required

#407 Migrate k8st onto kind dual stack cluster.
  Makefile
  tests/k8st/create_kind_cluster.sh
  tests/k8st/delete_kind_cluster.sh
  tests/k8st/dind-cluster-v1.12.sh
  tests/k8st/infra/calico-kdd.yaml
  tests/k8st/infra/calicoctl.yaml
  tests/k8st/infra/test-webserver.yaml
  tests/k8st/test_base.py
  tests/k8st/tests/test_bgp_advert.py
  tests/k8st/tests/test_ipip_spoofing.py
  tests/k8st/tests/test_simple.py
  tests/k8st/utils/utils.py
Labels: docs-pr-required, release-note-required

#408 Update base image to ubi-minimal:8.1-328
  Dockerfile.amd64
  centos.repo
  go.sum
Labels: docs-not-required, release-note-not-required

#410 release-v3.11 - Cherry-pick build fix, base image update
  Dockerfile.amd64
  centos.repo
Labels: docs-not-required, release-note-required

#411 Ensure appending to PUSH_IMAGES is not part of a recipe
  Makefile
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#413 Cherry-pick Ensure appending to PUSH_IMAGES is not part of a recipe (#411)
  Makefile
Labels: docs-pr-required, release-note-required

#412 Fix GIT_VERSION running make k8st from semaphore v2
  .semaphore/semaphore.yml
Labels: docs-pr-required, release-note-required

#416 Restructure BGP tests to avoid double setup for RR test
  tests/k8st/tests/test_bgp_advert.py
  tests/k8st/tests/test_bgp_advert_v6.py
Labels: docs-not-required, release-note-not-required

#418 add protocols section in nsswitch.conf
  filesystem/etc/nsswitch.conf
Labels: docs-not-required, release-note-required

#419 Improve the name that Semaphore v2 displays
  .semaphore/semaphore.yml
Labels: docs-not-required, release-note-not-required
