Repository projectcalico/node, pull requests merged in 2020-07, with the labels that each got.

#526 Include setup in the keep-list of packages.
  clean-up-filesystem.sh
Labels: docs-not-required, release-note-not-required

#528 Update confd pin
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#534 Use calicoctl-wait instead of now non-existent shell, in calicoctl image
  tests/k8st/infra/calicoctl-etcd.yaml
  tests/k8st/infra/calicoctl.yaml
Labels: docs-not-required, release-note-not-required

#531 Always auto-detect node IP address
  pkg/startup/startup.go
Labels: docs-not-required, release-note-required

#535 Update cni-plugin command
  Makefile
  go.sum
  tests/k8st/infra/calico-etcd.yaml
  tests/k8st/infra/calico-kdd.yaml
  tests/st/utils/workload.py
Labels: docs-not-required, release-note-not-required

#536 Build as root if UID 0
  Makefile
Labels: docs-not-required, release-note-not-required

#537 Automated cherry pick of #536: Update go-build version to v0.45
  Makefile
Labels: docs-not-required, release-note-not-required

#538 Upgrade to Golang 1.14
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#518 Introduce detection method cidr
  pkg/allocateip/allocateip.go
  pkg/startup/autodetection/filtered.go
  pkg/startup/autodetection/filtered_test.go
  pkg/startup/startup.go
Labels: docs-pr-required, release-note-required

#539 Fix outdate gomod/sum
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required
