Repository projectcalico/node, pull requests merged in 2020-11, with the labels that each got.

#616 Bump golang to 1.15
  Makefile
  go.mod
Labels: docs-pr-required, release-note-required

#614 [master] Automatic update of sempahore YAMLs.
  .semaphore/semaphore.yml
  .semaphore/update_pins.yml
Labels: docs-pr-required, release-note-required

#617 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#618 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#619 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#620 Fix release branch pin update regex (add ^ to start)
  .semaphore/semaphore.yml
Labels: docs-not-required, release-note-not-required

#623 Update pins
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#624 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#625 Update pins
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#626 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#627 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#628 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#629 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#630 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#632 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#634 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#637 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#639 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#641 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#640 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#643 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#644 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#645 windows: restore metadata route for GCE too if missing
  windows-packaging/CalicoWindows/libs/calico/calico.psm1
  windows-packaging/CalicoWindows/node/node-service.ps1
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#646 pick: windows: restore metadata route for GCE too if missing (#645)
  windows-packaging/CalicoWindows/libs/calico/calico.psm1
  windows-packaging/CalicoWindows/node/node-service.ps1
Labels: docs-pr-required, release-note-required

#653 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#654 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#655 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#593 Automatically find the cidr of IPv4Address when IP is ipStr
  pkg/startup/startup.go
  pkg/startup/startup_test.go
Labels: docs-pr-required, release-note-required

#657 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#652 Add missing env SVDIR for sv
  Dockerfile.arm64
  Dockerfile.ppc64le
  Dockerfile.s390x
Labels: docs-not-required, release-note-required

#665 add cni to pin updates
  Makefile
  go.mod
  go.sum
  pkg/startup/startup.go
  pkg/startup/startup_test.go
Labels: docs-not-required, release-note-not-required

#666 [master] Semaphore Auto Pin Update
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#669 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#668 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#670 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#671 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#673 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required
