Repository projectcalico/node, pull requests merged in 2020-04, with the labels that each got.

#458 Update tests for KubeControllersConfiguration
  go.mod
  go.sum
  pkg/allocateip/allocateip_test.go
Labels: docs-not-required, release-note-not-required

#457 [phone home] Distinguish Rancher deployments
  pkg/startup/startup.go
  pkg/startup/startup_test.go
Labels: docs-not-required, release-note-not-required

#460 Pin ubi-minimal to 8.1-407 for now
  Dockerfile.amd64
  tests/k8st/infra/calico-etcd.yaml
  tests/k8st/infra/calico-kdd.yaml
  tests/k8st/tests/test_bgp_advert_v6.py
Labels: docs-pr-required, release-note-required

#451 Set component in log formatter
  cmd/calico-node/main.go
  go.mod
  go.sum
  pkg/allocateip/allocateip.go
  pkg/startup/startup.go
Labels: docs-not-required, release-note-not-required

#462 [cherry-pick] Fix kubeadm auto-detection
  pkg/startup/startup.go
  pkg/startup/startup_test.go
  tests/k8st/tests/test_bgp_advert_v6.py
Labels: docs-not-required, release-note-required

#465 Update felix and libcalico pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#466 Update libcalico-go and felix pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#323 K8ST: Better code for DaemonSet update
  tests/k8st/test_base.py
  tests/k8st/tests/test_bgp_advert.py
  tests/k8st/tests/test_bgp_advert_v6.py
Labels: docs-not-required, release-note-not-required

#468 Fix order of parameters to validateBlocksize
  pkg/startup/startup.go
Labels: docs-pr-required, release-note-required

#474 Fix tests and update pins
  Makefile
  go.mod
  go.sum
  tests/st/policy/test_profile.py
  tests/st/utils/docker_host.py
Labels: docs-not-required, release-note-not-required

#475 Rev felix to pick up BPF RPF updates.
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#476 Move pin update job to promotion so it can be manually triggered.
  .semaphore/push-images.yml
  .semaphore/semaphore.yml
  .semaphore/update-pins.yml
Labels: docs-not-required, release-note-not-required

#461 Add GlobalNetworkPolicy short name
  tests/k8st/infra/calico-kdd.yaml
Labels: docs-not-required, release-note-not-required

#472 Follow on to validateBlocksize update
  pkg/startup/startup.go
  pkg/startup/startup_test.go
Labels: docs-not-required, release-note-not-required

#477 Remove auto-promotion of update-pins hook
  .semaphore/semaphore.yml
  .semaphore/update-pins.yml
Labels: docs-pr-required, release-note-required

#478 Semaphore: Fix PR check
  .semaphore/push-images.yml
Labels: docs-not-required, release-note-not-required

#479 Update the semaphore cd
  .semaphore/push-images.yml
Labels: docs-not-required, release-note-not-required

#480 Add the BRANCH_NAME for semaphore cd
  .semaphore/push-images.yml
Labels: docs-not-required, release-note-not-required

#481 Semaphore: Build all images with cd
  .semaphore/push-images.yml
Labels: docs-pr-required, release-note-required

#482 Semaphore: push needs docker credentials
  .semaphore/push-images.yml
Labels: docs-pr-required, release-note-required

#464 Fix bird health check return error message when BIRD service report "connect: resource temporarily unavailable"
  pkg/health/bird/bird.go
Labels: docs-not-required, release-note-required

#433 add goreportcard
  README.md
  pkg/allocateip/allocateip_test.go
  pkg/health/bird/bird.go
  pkg/startup/startup.go
  pkg/startup/startup_test.go
Labels: docs-not-required, release-note-not-required

#483 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required
