Repository projectcalico/node, pull requests merged in 2021-11, with the labels that each got.

#1308 Split cd semaphore job
  .semaphore/semaphore.yml
Labels: docs-pr-required, release-note-not-required

#1306 Set empty node status if BGP is not enabled.
  pkg/status/nodestatus_test.go
  pkg/status/populators/bird_conn.go
  pkg/status/populators/bird_status.go
  pkg/status/populators/peers.go
  pkg/status/populators/route.go
Labels: release-note-required, docs-pr-required

#1300 Check and install Windows upgrade service
  cmd/calico-node/main.go
  pkg/winupgrade/k8s_resources.go
  pkg/winupgrade/should_upgrade.go
  pkg/winupgrade/upgrade.go
  pkg/winupgrade/upgrade_suite_test.go
  pkg/winupgrade/upgrade_test.go
  windows-packaging/CalicoWindows/node/node-service.ps1
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#1312 Automated cherry pick of #1300: Update how Windows upgrade service started.
  cmd/calico-node/main.go
  pkg/winupgrade/k8s_resources.go
  pkg/winupgrade/should_upgrade.go
  pkg/winupgrade/upgrade.go
  pkg/winupgrade/upgrade_suite_test.go
  pkg/winupgrade/upgrade_test.go
  windows-packaging/CalicoWindows/node/node-service.ps1
Labels: docs-not-required, release-note-not-required

#1310 Automated cherry pick of #1308: Split cd semaphore job up
  .semaphore/semaphore.yml
Labels: docs-not-required, release-note-not-required

#1244 Update docker images and centos repos to address CVE false positives
  .semaphore/semaphore.yml
  Dockerfile.amd64
  centos.repo
  clean-up-filesystem.sh
  tests/k8st/infra/calico-kdd.yaml
Labels: release-note-required, docs-not-required

#1314 Fix tests
  .semaphore/semaphore.yml
  tests/k8st/infra/calico-kdd.yaml
Labels: docs-not-required, release-note-not-required

#1315 [release-v3.21] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1313 Merge pull request #1306 from song-jiang/song-node-status
  pkg/status/nodestatus_test.go
  pkg/status/populators/bird_conn.go
  pkg/status/populators/bird_status.go
  pkg/status/populators/peers.go
  pkg/status/populators/route.go
Labels: release-note-required, docs-pr-required

#1319 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1316 [release-v3.18] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1322 Update confd pins for disableBGPExport support
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#1318 windows: verify upgrade image using node pod
  pkg/winupgrade/k8s_resources.go
  pkg/winupgrade/upgrade.go
  windows-upgrade/calico-upgrade.ps1
Labels: release-note-required, docs-not-required

#1323 Automated cherry pick of #1318: windows: verify upgrade image using node pod
  pkg/winupgrade/k8s_resources.go
  pkg/winupgrade/upgrade.go
  windows-upgrade/calico-upgrade.ps1
Labels: release-note-required, docs-not-required

#1320 [release-v3.21] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1324 [release-v3.21] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1325 [release-v3.21] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1329 [release-v3.21] Auto pick #1322: Update confd pins for disableBGPExport support #1328: Update confd pin for disableBGPExport fix
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready

#1328 Update confd pin for disableBGPExport fix
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready

#1331 Automated cherry pick of #1330: windows: fix entrypoint not deleting the outer zip file
  windows-upgrade/Dockerfile
Labels: docs-not-required, release-note-not-required

#1334 [release-v3.21] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1335 Add disableBGPExport ST test case
  tests/st/bgp/test_bgp.py
Labels: docs-not-required, release-note-not-required

#1336 Increase node patch timeout for shutdown
  pkg/lifecycle/shutdown/shutdown.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#1340 [release-v3.21] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1341 Automated cherry pick of #1336: Increase node patch timeout for shutdown
  pkg/lifecycle/shutdown/shutdown.go
Labels: release-note-required, docs-not-required

#1330 windows: fix entrypoint not deleting the outer zip file
  windows-upgrade/Dockerfile
Labels: docs-not-required, release-note-not-required

#1338 Improve handling CalicoUpgrade service
  pkg/lifecycle/utils/utils.go
  pkg/winupgrade/should_upgrade.go
  pkg/winupgrade/upgrade.go
  windows-packaging/CalicoWindows/stop-calico.ps1
  windows-packaging/CalicoWindows/uninstall-calico.ps1
Labels: release-note-required, docs-pr-required

#1343 Merge pull request #1338 from song-jiang/song-win-aks
  pkg/lifecycle/utils/utils.go
  pkg/winupgrade/should_upgrade.go
  pkg/winupgrade/upgrade.go
  windows-packaging/CalicoWindows/stop-calico.ps1
  windows-packaging/CalicoWindows/uninstall-calico.ps1
Labels: release-note-required, docs-not-required

#1344 Update centos.repo now that 8.4.2105 is deprecated
  centos.repo
Labels: docs-not-required, release-note-not-required

#1345 Automated cherry pick of #1344: Update centos.repo now that 8.4.2105 is deprecated
  centos.repo
Labels: docs-not-required, release-note-not-required

#1346 Automated cherry pick of #1344: Update centos.repo now that 8.4.2105 is deprecated
  centos.repo
  tests/k8st/infra/calico-kdd.yaml
Labels: docs-not-required, release-note-not-required

#1348 Automated cherry pick of #1344: Update centos.repo now that 8.4.2105 is deprecated
  centos.repo
Labels: docs-not-required, release-note-not-required

#1350 [release-v3.21] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1351 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1353 Automated cherry pick of #1352: windows: don't push release images to gcr
  Makefile
Labels: docs-not-required, release-note-not-required

#1354 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1355 [release-v3.18] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1352 windows: don't push release images to gcr
  Makefile
Labels: docs-not-required, release-note-not-required

#1349 Add newline to final fmt.Printf calls
  pkg/calicoclient/calicoclient.go
  pkg/health/health.go
Labels: release-note-required, docs-not-required

#1357 [release-v3.18] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1356 Make more room on the semaphore build machine
  .semaphore/semaphore.yml
Labels: docs-not-required, release-note-not-required

#1359 Automated cherry pick of #1356: Make more room on the semaphore build machine
  .semaphore/semaphore.yml
Labels: docs-not-required, release-note-not-required

#1361 [release-v3.21] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1363 Update felix pin
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1358 Added node status ST
  tests/k8st/deploy_resources_on_kind_cluster.sh
  tests/k8st/tests/test_node_status.py
Labels: release-note-required, docs-pr-required

#1364 update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#1365 Merge pull request #1358 from song-jiang/song-node-st
  tests/k8st/deploy_resources_on_kind_cluster.sh
  tests/k8st/tests/test_node_status.py
Labels: release-note-required, docs-pr-required

#1367 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1368 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch
