Repository projectcalico/node, pull requests merged in 2021-08, with the labels that each got.

#1107 [release-v3.19] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1130 [release-v3.19] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1126 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1133 Send logs both to file and kubectl logs
  filesystem/etc/service/available/allocate-tunnel-addrs/log/run
  filesystem/etc/service/available/bird/log/run
  filesystem/etc/service/available/bird6/log/run
  filesystem/etc/service/available/calico-bgp-daemon/log/run
  filesystem/etc/service/available/cni/log/run
  filesystem/etc/service/available/confd/log/run
  filesystem/etc/service/available/felix/log/run
  tests/st/utils/log_analyzer.py
Labels: release-note-required, docs-pr-required

#1134 Merge pull request #1133 from song-jiang/song-felix-log
  filesystem/etc/service/available/allocate-tunnel-addrs/log/run
  filesystem/etc/service/available/bird/log/run
  filesystem/etc/service/available/bird6/log/run
  filesystem/etc/service/available/calico-bgp-daemon/log/run
  filesystem/etc/service/available/cni/log/run
  filesystem/etc/service/available/confd/log/run
  filesystem/etc/service/available/felix/log/run
  tests/st/utils/log_analyzer.py
Labels: release-note-required, docs-pr-required

#1131 [release-v3.19] Semaphore Auto Pin Update
  .semaphore/semaphore.yml
  Makefile
  go.mod
  go.sum
  tests/k8st/create_kind_cluster.sh
  tests/k8st/infra/calicoctl-etcd.yaml
  tests/k8st/infra/calicoctl.yaml
Labels: docs-not-required, release-note-not-required

#1135 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#1136 Update docker images and centos repos to address CVE false positives
  Dockerfile.amd64
  centos.repo
  clean-up-filesystem.sh
Labels: docs-not-required, release-note-not-required

#1139 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1140 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1142 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1143 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1145 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1146 Change release repo to docker.io, add RELEASE and CONFIRM env variables
  Makefile
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1147 Automated cherry pick of #1146: Change release repo to docker.io, add RELEASE and CONFIRM env
  Makefile
Labels: docs-not-required, release-note-not-required

#1149 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1148 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1151 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1152 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1153 Increase the automation time for creating images
  .semaphore/semaphore.yml
Labels: docs-not-required, release-note-not-required

#1154 Increase the automation time for creating images
  .semaphore/semaphore.yml
Labels: docs-not-required, release-note-not-required

#1141 Update docker images and centos repos to address CVE false positives
  Dockerfile.amd64
  centos.repo
  clean-up-filesystem.sh
Labels: release-note-required, docs-not-required

#1157 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1158 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1159 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1156 windows: replace WMI cmdlet usage with CIM
  windows-packaging/CalicoWindows/libs/calico/calico.psm1
Labels: release-note-required, docs-pr-required

#1155 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1160 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1144 [release-v3.18] Semaphore Auto Pin Update
  Makefile
  go.mod
  go.sum
  tests/k8st/create_kind_cluster.sh
  tests/k8st/infra/calicoctl-etcd.yaml
  tests/k8st/infra/calicoctl.yaml
Labels: docs-not-required, release-note-not-required

#1161 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1162 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1170 Pin to Calico-owned scapy image.
  tests/k8st/tests/test_ipip_spoofing.py
Labels: release-note-required, docs-pr-required, merge-when-ready

#1172 [release-v3.19] Auto pick #1170: Pin to Calico-owned scapy image.
  tests/k8st/tests/test_ipip_spoofing.py
Labels: release-note-required, docs-pr-required

#1173 [release-v3.18] Auto pick #1170: Pin to Calico-owned scapy image.
  tests/k8st/tests/test_ipip_spoofing.py
Labels: release-note-required, docs-pr-required

#1171 [origin/release-v3.20] Auto cherry pick of #1170: Pin to Calico-owned scapy image.
  tests/k8st/tests/test_ipip_spoofing.py
Labels: release-note-required, docs-pr-required

#1179 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1174 [release-v3.17] Auto pick #1170: Pin to Calico-owned scapy image.
  Makefile
  tests/k8st/create_kind_cluster.sh
  tests/k8st/infra/calicoctl-etcd.yaml
  tests/k8st/infra/calicoctl.yaml
  tests/k8st/tests/test_ipip_spoofing.py
Labels: release-note-required, docs-pr-required

#1180 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1181 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1164 [release-v3.19] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1168 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1176 [release-v3.18] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1184 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1183 Fix build
  Dockerfile.amd64
  tests/k8st/create_kind_cluster.sh
  tests/k8st/tests/test_ipip_spoofing.py
Labels: release-note-required, docs-pr-required

#1186 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1185 Rev felix to pick up namespace performance fix.
  .semaphore/semaphore.yml
  go.mod
  go.sum
Labels: release-note-required, docs-pr-required

#1188 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1189 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1166 Configurable VXLAN adapter
  windows-packaging/CalicoWindows/config.ps1
  windows-packaging/CalicoWindows/node/node-service.ps1
Labels: release-note-required, docs-pr-required

#1044 eBPF arm64/aarch64
  Dockerfile.arm64
  Makefile
Labels: release-note-required, docs-not-required
