Repository projectcalico/node, pull requests merged in 2021-05, with the labels that each got.

#984 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#986 [release-v3.19] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#988 [release-v3.19] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#989 [release-v3.19] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#990 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#994 [release-v3.19] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#996 Retry KIND cluster setup
  tests/k8st/create_kind_cluster.sh
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#997 Update libcalico-go pin
  Dockerfile.amd64
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#995 Refactor makefile for new cd / release flow
  Makefile
Labels: docs-not-required, release-note-not-required

#999 [release-v3.18] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1001 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#993 Added shutdown package to handle cailco-node shutdown
  cmd/calico-node/main.go
  pkg/lifecycle/shutdown/shutdown.go
  pkg/lifecycle/startup/autodetection/autodetection_suite_test.go
  pkg/lifecycle/startup/autodetection/filtered.go
  pkg/lifecycle/startup/autodetection/filtered_test.go
  pkg/lifecycle/startup/autodetection/interfaces.go
  pkg/lifecycle/startup/autodetection/ipv4/poolselector.go
  pkg/lifecycle/startup/autodetection/ipv4/poolselector_test.go
  pkg/lifecycle/startup/autodetection/ipv4/poolselector_windows.go
  pkg/lifecycle/startup/autodetection/reachaddr.go
  pkg/lifecycle/startup/startup.go
  pkg/lifecycle/startup/startup_linux.go
  pkg/lifecycle/startup/startup_suite_test.go
  pkg/lifecycle/startup/startup_test.go
  pkg/lifecycle/startup/startup_windows.go
  pkg/lifecycle/utils/utils.go
  pkg/nodeinit/calico-init_linux.go
Labels: docs-not-required, release-note-required

#1002 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1005 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1006 Fix Make file for startup package path change
  Makefile
Labels: docs-pr-required, release-note-required
