Repository projectcalico/node, pull requests merged in 2021-06, with the labels that each got.

#1008 Enable management of CNI plugins by default
  filesystem/etc/rc.local
Labels: docs-pr-required, release-note-required

#1007 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1010 update dockerfile and iptables version to get build working
  Dockerfile.amd64
Labels: docs-not-required, merge-when-ready, release-note-not-required

#1011 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1012 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1013 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1014 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1017 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1020 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1019 Fix sem timeouts and priorities
  .semaphore/semaphore.yml
  .semaphore/update_pins.yml
Labels: docs-pr-required, release-note-required

#1021 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1022 Fix sem timeouts and priorities
  .semaphore/semaphore.yml
  .semaphore/update_pins.yml
Labels: delete-branch, docs-pr-required, merge-when-ready, release-note-required

#800 added armhf architecture support
  Dockerfile.armv7
  Makefile
Labels: docs-pr-required, release-note-required

#1023 Replace lib/v3 package with projectcalico/api
  go.mod
  go.sum
  pkg/allocateip/allocateip.go
  pkg/allocateip/allocateip_test.go
  pkg/allocateip/test_utils.go
  pkg/lifecycle/startup/startup.go
  pkg/lifecycle/startup/startup_test.go
Labels: docs-not-required, merge-when-ready, release-note-not-required

#1025 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1026 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1027 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1028 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1029 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1031 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1033 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1035 upgrade go-build from v0.53 to v0.54.
  Makefile
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#1037 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1038 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1036 Update api pins on pin update
  Makefile
Labels: docs-not-required, release-note-not-required

#1042 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1045 Update version of CentOS used for pulling packages when building the calico-node image
  centos.repo
Labels: docs-pr-required, release-note-required

#1046 Automated cherry pick of #1045: Update cent OS repo
  centos.repo
Labels: docs-pr-required, merge-when-ready, release-note-required

#1047 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1018 windows: set kube-proxy IPv6DualStack=false for VXLAN
  windows-packaging/CalicoWindows/kubernetes/kube-proxy-service.ps1
Labels: docs-pr-required, release-note-required

#1048 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required
