Repository projectcalico/node, pull requests merged in 2021-07, with the labels that each got.

#1049 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1050 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1051 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1052 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1053 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1054 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1055 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1058 Update BIRD to allow 240.0.0.0/8 IPs
  Makefile
Labels: docs-not-required, release-note-not-required

#1061 Update call to AutoAssign() to use IPAMAssignments struct
  go.mod
  go.sum
  pkg/allocateip/allocateip.go
Labels: docs-not-required, release-note-not-required

#1065 Update BIRD again, for fixed 240/8 network support
  Makefile
Labels: docs-not-required, release-note-not-required

#1066 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1068 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1064 windows: create VXLAN tunnel address in node
  go.mod
  go.sum
  pkg/lifecycle/startup/startup_windows.go
Labels: docs-not-required, release-note-required

#1070 [release-v3.19] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1069 [release-v3.18] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1072 [release-v3.19] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1073 [release-v3.18] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1074 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1077 [release-v3.19] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1080 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1081 [release-v3.18] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1085 Update confd pins
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#1084 Update confd pins
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#982 Bump alpine version to 3.13
  Dockerfile.arm64
Labels: docs-not-required, release-note-not-required

#1086 Fix node update conflict on startup
  pkg/lifecycle/startup/startup.go
Labels: docs-pr-required, merge-when-ready, release-note-required

#1087 Update pins
  go.mod
  go.sum
  tests/k8st/infra/calico-kdd.yaml
Labels: docs-not-required, release-note-not-required

#1088 Automated cherry pick of #1087: Update pins
  go.mod
  go.sum
  tests/k8st/infra/calico-kdd.yaml
Labels: docs-pr-required, release-note-required

#1089 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1091 Merge pull request #1086 from song-jiang/song-fix-restart
  pkg/lifecycle/startup/startup.go
Labels: docs-pr-required, release-note-required

#1092 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1093 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1094 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1096 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1097 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
  tests/k8st/create_kind_cluster.sh
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1101 Fix kube-proxy crashloopback for kind cluster
  tests/k8st/create_kind_cluster.sh
Labels: docs-pr-required, release-note-required

#1099 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1105 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1103 Allow version mismatch in tests
  tests/k8st/infra/calicoctl-etcd.yaml
  tests/k8st/infra/calicoctl.yaml
  tests/k8st/utils/utils.py
  tests/st/utils/docker_host.py
Labels: docs-not-required, merge-when-ready, release-note-not-required

#1108 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#1110 Update release targets
  Makefile
Labels: docs-pr-required, release-note-required

#1111 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1112 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1114 Update release targets
  Makefile
Labels: docs-not-required, release-note-not-required

#1115 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1116 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1113 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1118 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1119 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1120 Fix release image tagging
  Makefile
Labels: docs-not-required, release-note-not-required

#1121 Automated cherry pick of #1120: Fix release image tagging
  Makefile
Labels: docs-pr-required, release-note-required

#1122 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1123 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1124 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1125 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1127 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required
