Repository projectcalico/node, pull requests merged in 2021-04, with the labels that each got.

#905 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#885 Bump ubi:8.1 to 8.3 to get latest security fixes
  Dockerfile.amd64
Labels: docs-not-required, merge-when-ready, release-note-required

#908 [release-v3.18] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#909 [release-v3.18] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#912 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#913 [master] Semaphore Auto Pin Update
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#916 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#920 Clean Makefile
  Makefile
Labels: docs-not-required, merge-when-ready, release-note-not-required

#922 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#923 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#924 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#926 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#927 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#929 [release-v3.18] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#931 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#930 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#934 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#935 Move variable definitions above include of common makefile.
  Makefile
Labels: docs-not-required, release-note-required

#936 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#937 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#939 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#933 Update windows packaging to support containerd
  windows-packaging/CalicoWindows/cni.conf.template
  windows-packaging/CalicoWindows/config.ps1
  windows-packaging/CalicoWindows/kubernetes/kubelet-service.ps1
  windows-packaging/CalicoWindows/libs/calico/calico.psm1
Labels: docs-pr-required, release-note-required

#940 [release-v3.18] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#938 fix(startup): panic when ip pool cidr parse error
  pkg/startup/startup.go
Labels: docs-not-required, merge-when-ready, release-note-not-required

#878 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#941 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#943 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#944 Handle mismatched nodenames when setting NetworkUnavailable
  pkg/startup/startup.go
Labels: docs-not-required, release-note-required

#946 Automated cherry pick of #944: Handle mismatched nodenames when setting NetworkUnavailable
  pkg/startup/startup.go
Labels: docs-pr-required, release-note-required

#947 Automated cherry pick of #944: Handle mismatched nodenames when setting NetworkUnavailable
  pkg/startup/startup.go
Labels: docs-pr-required, release-note-required

#948 Automated cherry pick of #944: Handle mismatched nodenames when setting NetworkUnavailable
  pkg/startup/startup.go
Labels: docs-pr-required, release-note-required

#949 Automated cherry pick of #944: Handle mismatched nodenames when setting NetworkUnavailable
  pkg/startup/startup.go
Labels: docs-pr-required, release-note-required

#951 [release-v3.19] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#953 Update packages to pick up security updates
  Dockerfile.amd64
Labels: docs-not-required, release-note-not-required

#955 Add calico-node -init command to mount bpffs.
  cmd/calico-node/main.go
  pkg/nodeinit/calico-init_linux.go
  pkg/nodeinit/calico-init_windows.go
Labels: cherry-pick-candidate, docs-pr-required, merge-when-ready, release-note-required

#957 [v3.19] Add calico-node -init command to mount bpffs.
  cmd/calico-node/main.go
  pkg/nodeinit/calico-init_linux.go
  pkg/nodeinit/calico-init_windows.go
Labels: docs-pr-required, release-note-required

#950 [release-v3.18] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#960 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#962 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#964 [release-v3.18] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#966 [release-v3.19] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#974 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#975 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#977 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#978 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#979 [release-v3.18] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#980 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required
