Repository projectcalico/node, pull requests merged in 2021-10, with the labels that each got.

#1231 [release-v3.19] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1230 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1232 [release-v3.18] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1233 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1226 Update Kubernetes version used in tests
  .gitignore
  Makefile
  go.mod
  go.sum
  pkg/allocateip/allocateip.go
  tests/k8st/delete_kind_cluster.sh
  tests/k8st/deploy_resources_on_kind_cluster.sh
  tests/k8st/infra/calico-etcd.yaml
  tests/k8st/infra/calico-kdd.yaml
  tests/k8st/infra/calicoctl-etcd.yaml
  tests/k8st/infra/calicoctl.yaml
  tests/k8st/infra/test-webserver.yaml
  tests/k8st/test_base.py
  tests/k8st/tests/test_bgp_advert.py
  tests/k8st/tests/test_bgp_advert_v6.py
  tests/k8st/tests/test_ipip_spoofing.py
  tests/k8st/tests/test_simple.py
  tests/k8st/utils/utils.py
  tests/kind-config.yaml
Labels: release-note-required, docs-pr-required

#1224 Run Calico node as non-root user
  Dockerfile.amd64
Labels: release-note-required, docs-pr-required

#1237 Squash spammy log in autodetect code
  pkg/lifecycle/startup/autodetection/reachaddr.go
Labels: release-note-required, docs-not-required

#1243 Update docker images and centos repos to address CVE false positives
  Dockerfile.amd64
  centos.repo
  clean-up-filesystem.sh
Labels: release-note-required, docs-not-required

#1246 Add static check for boringssl usage
  Makefile
Labels: docs-not-required, release-note-not-required

#1248 Prevent attempts to create hostpath volumes twice during initialization
  pkg/hostpathinit/hostpath_init.go
Labels: docs-not-required, release-note-not-required

#1267 windows: normalize line endings
  .gitattributes
  windows-packaging/CalicoWindows/confd/confd-service.ps1
  windows-packaging/CalicoWindows/config.ps1
  windows-packaging/CalicoWindows/felix/felix-service.ps1
  windows-packaging/CalicoWindows/install-calico.ps1
  windows-packaging/CalicoWindows/kubernetes/install-kube-services.ps1
  windows-packaging/CalicoWindows/kubernetes/kube-proxy-service.ps1
  windows-packaging/CalicoWindows/kubernetes/kubelet-service.ps1
  windows-packaging/CalicoWindows/kubernetes/uninstall-kube-services.ps1
  windows-packaging/CalicoWindows/libs/calico/calico.psm1
  windows-packaging/CalicoWindows/node/node-service.ps1
  windows-packaging/CalicoWindows/start-calico.ps1
  windows-packaging/CalicoWindows/stop-calico.ps1
  windows-packaging/CalicoWindows/uninstall-calico.ps1
  windows-packaging/CalicoWindows/upgrade/upgrade-service.ps1
Labels: release-note-required, docs-pr-required

#1270 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1274 [release-v3.21] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1278 Build calico windows upgrade image
  .semaphore/semaphore.yml
  Makefile
  windows-upgrade/Dockerfile
  windows-upgrade/calico-upgrade.ps1
Labels: release-note-required, cherry-pick-candidate, docs-pr-required
