Repository projectcalico/node, pull requests merged in 2021-12, with the labels that each got.

#1366 windows: move install-calico-windows.ps1 here
  Makefile
  hack/gen-install-calico-windows-script/main.go
  windows-packaging/install-calico-windows.ps1.tpl
Labels: docs-pr-required, release-note-not-required

#1371 windows: pass ExceptUpgradeService param to stop-calico.ps1 as well
  windows-packaging/CalicoWindows/uninstall-calico.ps1
Labels: release-note-required, docs-not-required

#1372 [v3.21] Pick windows: pass ExceptUpgradeService param to stop-calico.ps1 as well
  windows-packaging/CalicoWindows/uninstall-calico.ps1
Labels: release-note-required, docs-not-required

#1375 [release-v3.21] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1374 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1376 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1378 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1242 New autodetection method KubernetesInternalIP added
  pkg/lifecycle/startup/autodetection/autodetection_linux.go
  pkg/lifecycle/startup/autodetection/autodetection_methods.go
  pkg/lifecycle/startup/autodetection/autodetection_windows.go
  pkg/lifecycle/startup/startup.go
  pkg/lifecycle/startup/startup_linux.go
  pkg/lifecycle/startup/startup_test.go
  pkg/lifecycle/startup/startup_windows.go
  pkg/lifecycle/utils/utils.go
Labels: release-note-required, docs-pr-required

#1373 [release-v3.21] Automated cherry pick of #1366: windows: move install-calico-windows.ps1 here
  Makefile
  hack/gen-install-calico-windows-script/main.go
  windows-packaging/install-calico-windows.ps1.tpl
Labels: release-note-required, docs-not-required, merge-when-ready, delete-branch

#1380 [release-v3.20] Automated cherry pick of #1373: windows: move install-calico-windows.ps1 here
  Makefile
  hack/gen-install-calico-windows-script/main.go
  windows-packaging/install-calico-windows.ps1.tpl
Labels: release-note-required, docs-not-required, merge-when-ready, delete-branch

#1381 [release-v3.19] Automated cherry pick of #1380: windows: move install-calico-windows.ps1 here
  Makefile
  hack/gen-install-calico-windows-script/main.go
  windows-packaging/install-calico-windows.ps1.tpl
Labels: release-note-required, docs-not-required, merge-when-ready, delete-branch
