Repository projectcalico/node, pull requests merged in 2021-01, with the labels that each got.

#745 Log version at startup
  pkg/startup/startup.go
Labels: docs-not-required, release-note-not-required

#746 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#748 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#749 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#750 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#753 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#743 Enrich info messages
  pkg/startup/startup.go
Labels: docs-not-required, merge-when-ready, release-note-not-required

#754 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#755 Bump alpine version for arm64
  Dockerfile.arm64
Labels: docs-not-required, release-note-required

#756 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#742 Add test for service advertisement node exclusion
  tests/k8st/tests/test_bgp_advert.py
Labels: docs-not-required, release-note-not-required

#744 Add test for LoadBalancer IP advertisement
  tests/k8st/create_kind_cluster.sh
  tests/k8st/infra/metallb-config.yaml
  tests/k8st/infra/metallb.yaml
  tests/k8st/tests/test_bgp_advert.py
Labels: docs-not-required, release-note-not-required

#759 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#762 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#765 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required
