Repository projectcalico/node, pull requests merged in 2022-02, with the labels that each got.

#1385 Update to UBI 8.5 and go-build v0.54
  Dockerfile.amd64
Labels: release-note-required, docs-pr-required

#1386 Update UBI to 8.5
  Dockerfile.amd64
Labels: release-note-required, docs-not-required

#1389 [release-v3.19] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1390 [release-v3.19] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch
